keys:
  - &think1clift age1q5vgzy4ztfvqu2n5x5ktcy7xytawhqeuzu7cgsqm49d8rn76esksekyx0u
  - &joseph age17er3p56wlm5y840gjamz7hpgmp0mxyall0s6sn5t22wkqu746fvq2l9hsu

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *think1clift
          - *joseph
  - path_regex: secrets/cloudflare-tunnel$
    key_groups:
      - age:
          - *think1clift
          - *joseph
  - path_regex: secrets/mullvad-wg\.conf$
    key_groups:
      - age:
          - *think1clift
          - *joseph