keys:
  # Add your machine's age public key here after running install.sh
  # The key is printed during install under "Converting initrd public SSH host key into public age key for sops-nix"
  - &think1clift age1ek0npcn04kva8gn4jm76tza5yrwtfgk2mtyhykhvuxpfam3et5xqyp8jx4

  - path_regex: secrets/[^/]+(\.(yaml|json|env|ini|conf))?$
    key_groups:
      - age:
          - *think1clift
